### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by chemalatha** [peterkimzz/aws-ssm-send-command#3]
peterkimzz/aws-ssm-send-command@0.0.2 - accepts instance-ids, but given this instance_id seems to be error popsup.

**Comment by peterkimzz** [comment]
Hi chemalatha,

0.0.2 version is outdated, so please use `1.0.1` version.

```yaml
uses: peterkimzz/aws-ssm-send-command@1.0.1
```

**Comment by fdiaspp** [comment]
Hello guys.

I'm having some trouble with **instance_ids** of the current version.

```
Run peterkimzz/aws-ssm-send-command@1.0.1
/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

InvalidInstanceId: null
    at Request.extractError (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/1.0.1/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: null,
  code: 'InvalidInstanceId',
  time: 2020-06-01T14:35:26.073Z,
  requestId: '078ea4ba-a38e-4e66-b3fd-fc95d7b6aed5',
  statusCode: 400,
  retryable: false,
  retryDelay: 63.969686612002555
```

Says **InvalidInstanceId: null** but my code has it specified.

```
name: AWS SSM Send-Command | Deploy automtico na EC2

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@1.0.1
        id: ssm
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          instance-ids:  i-064ed83db29d2c39c
          working-directory: /home/ec2-user/beta
          command: git checkout master && git stash && git pull
          comment: Deploy da branch $GITHUB_REF por $GITHUB_ACTOR no $GITHUB_REPOSITORY Github Action($GITHUB_ACTION)

      # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
```


Some tip would be very very nive.
